echo "Terminal Docker tools aliases:"
echo " * alpine: launch an interactive alpine 3.11 container"
echo " * dive: inspect the layers of a Docker image"
echo " * ld: run lazydocker in a container"
echo " * phonito: analyze Docker images for vulnerabilities"
echo " * trivy: analyze Docker images for vulnerabilities"
